site_name: Log Hub

theme:
        name: material
        features:
                - navigation.tabs
                - navigation.expand
        favicon: images/aws-solutions.png
        logo: images/aws-solutions.png
        language: en

extra:
        generator: false
        copyright: Copyright &copy; 2020 - 2021 Amazon Web Services
        bucket: aws-gcr-solutions
        version: latest

plugins:
        - search
        - macros

markdown_extensions:
        - admonition
        - attr_list
        - pymdownx.details
        - pymdownx.superfences

nav:
        - Implementation Guide:
                  - Overview: index.md
                  - Architecture Overview: implementation-guide/architecture.md
                  - Getting Started:
                            - Overview: implementation-guide/getting-started/index.md
                            - Step 1. Launch Stack: implementation-guide/getting-started/1.launch-stack.md
                            - Step 2. Import Domain: implementation-guide/getting-started/2.import-domain-manual.md
                            - Step 3. Create Proxy: implementation-guide/getting-started/3.create-proxy.md
                            - Step 4. Ingest CloudTrail Logs: implementation-guide/getting-started/4.build-cloudtrail-pipeline.md
                            - Step 5. View Dashboard: implementation-guide/getting-started/5.view-dashboard.md
                  - Deployment: implementation-guide/deployment.md
                  - Domain Management:
                            - Overview: implementation-guide/domains/index.md
                            - Domain Operations: implementation-guide/domains/import.md
                            - Access Proxy: implementation-guide/domains/proxy.md
                            - Alarms: implementation-guide/domains/alarms.md
                  - Analytics Pipelines:
                            - Overview: implementation-guide/pipelines/index.md
                            - AWS Services:
                                      - Overview: implementation-guide/pipelines/aws-services/index.md
                                      - Amazon CloudTrail: implementation-guide/pipelines/aws-services/cloudtrail.md
                                      - Amazon S3: implementation-guide/pipelines/aws-services/s3.md
                                      - Amazon RDS/Aurora: implementation-guide/pipelines/aws-services/rds.md
                                      - Amazon CloudFront: implementation-guide/pipelines/aws-services/cloudfront.md
                                      - AWS Lambda: implementation-guide/pipelines/aws-services/lambda.md
                                      - Elastic Load Balancing: implementation-guide/pipelines/aws-services/elb.md
                                      - AWS WAF: implementation-guide/pipelines/aws-services/waf.md
                            - Applications:
                                      - Overview: implementation-guide/pipelines/applications/index.md
                                      - Fluent bit installation guide: implementation-guide/pipelines/applications/fluent-bit-install-guide.md
                                      - Collect Apache HTTP server logs: implementation-guide/pipelines/applications/apache.md
                                      - Collect Nginx logs: implementation-guide/pipelines/applications/nginx.md
                                      - Collect Single-line logs: implementation-guide/pipelines/applications/single-line-text.md
                                      - Collect Multiline-line logs: implementation-guide/pipelines/applications/multi-line-text.md
                                      - Collect JSON logs: implementation-guide/pipelines/applications/json.md
                  #      - Cost: implementation-guide/cost.md
                  - Additional Resources: implementation-guide/resources.md
        - FAQ:
                  - Overview: implementation-guide/faq.md
                  - Troubleshooting: implementation-guide/trouble-shooting.md
        - Roadmap:
                  - Overview: updates/roadmap.md
                  - Updates:
                            - Changelog: updates/changelog.md
                            - Sprints: updates/sprints.md
        - Technical Designs:
                  - Overview: designs/index.md
                  - Concepts: designs/concepts.md
                  - High Level Design: designs/solution/high-level-design.md
                  - Domain Management:
                            - Component Design: designs/domain-management/component-design.md
                            - Process Design: designs/domain-management/process-design.md
                            - API Design: designs/domain-management/api-design.md
                            - Data Model Design: designs/domain-management/data-model-design.md
                  - Service Log Analytics:
                            - Component Design: designs/service-log/component-design.md
                            - Process Design: designs/service-log/process-design.md
                            - API Design: designs/service-log/api-design.md
                            - Data Model Design: designs/service-log/data-model-design.md
                            - "Tutorial: Extend Service Logs": designs/service-log/tutorial-extend-service-log.md
                  - Application Log:
                            - Overview: designs/app-log/log-analytics-pipeline-app.md
                            - Architecture Design: designs/app-log/architecture-design.md
                            - Process Design: designs/app-log/process-design.md
                            - API Design: designs/app-log/api-design.md
                            - Data Model Design: designs/app-log/data-model-design.md
                  - UI Design:
                            - Updates: designs/ui-design-updates.md
                  - User Stories: designs/user-stories.md
                  - User Interface:
                            - Help Panel: designs/UI/help-panel.md
                  - Competitive Analysis:
                            - Overview: designs/competitive-study/index.md
                            - SLS: designs/competitive-study/sls.md
                  - Assets: designs/assets.md
        - Workshop:
                  - 1. Introduction: workshop/introduction.md
                  - 2. Pre-requisites:
                            - 2.0 Must Read: workshop/deployment/must-read.md
                            - 2.1 EC2 Key Pair: workshop/deployment/key-pair.md
                            - 2.2 Create service linked role: workshop/deployment/service-linked-role.md
                            - 2.3 Get ACM Certification: workshop/deployment/acm-certification.md
                            - 2.4 Deploy Demo Web Site: workshop/deployment/deploy-demo-web-site.md
                  - 3. Deploy Log Hub: workshop/deployment/deploy-log-hub.md
                  - 4. Domain Management:
                            - 4.1 Import Domain: workshop/domain-management/import-domain.md
                            - 4.2 Create Proxy: workshop/domain-management/create-proxy.md
                            - 4.3 Access Proxy: workshop/domain-management/access-proxy.md
                  - 5. Log Ingestion and Visualization:
                            - 5.1 Ingest Service Logs via Log Hub Console: workshop/log-analytics-pipelines/cloudfront-log.md
                            - 5.2 Ingest Application Logs via Log Hub Console: workshop/log-analytics-pipelines/application-log.md
                            - 5.3 Ingest Logs via CloudFormation Stack: workshop/log-analytics-pipelines/elb-log.md
                  - 6. Clean Up: workshop/clean-up.md
